title: The Kingdom of God
author: Marie Lee
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to a new world where we pull God and ourselves out of the box.

# social links
theme: slate
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
#github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
